<strong>Project</strong>: fabric<br><strong>Branch</strong>: master<br><strong>ID</strong>: 11029<br><strong>Subject</strong>: [FAB-4769] SysTest: Stop all Brokers; Restart 2<br><strong>Status</strong>: ABANDONED<br><strong>Owner</strong>: Latitia Haskins - latitia.haskins@gmail.com<br><strong>Assignee</strong>:<br><strong>Created</strong>: 6/22/2017, 3:26:52 PM<br><strong>LastUpdated</strong>: 6/28/2017, 12:26:52 PM<br><strong>CommitMessage</strong>:<br><pre>[FAB-4769] SysTest: Stop all Brokers; Restart 2

This behave base system test takes down all
kafka brokers and brings back only 2 brokers.
The 2 last brokers that went down stay down.
Based on the recommended kafka-based orderer
network (4 brokers, repl fac=3, insync=2),
an invoke will fail, but a query will return.

Change-Id: I33a5e88cb0fb83ab5d815f6439f73f930fba4e88
Signed-off-by: Latitia M Haskins <latitia.haskins@gmail.com>
</pre><h1>Comments</h1><strong>Reviewer</strong>: Latitia Haskins - latitia.haskins@gmail.com<br><strong>Reviewed</strong>: 6/22/2017, 3:26:52 PM<br><strong>Message</strong>: <pre>Uploaded patch set 1.</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 6/22/2017, 3:26:59 PM<br><strong>Message</strong>: <pre>Patch Set 1:

Build Started https://jenkins.hyperledger.org/job/fabric-verify-z/9408/ (1/4)</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 6/22/2017, 3:29:44 PM<br><strong>Message</strong>: <pre>Patch Set 1:

Build Started https://jenkins.hyperledger.org/job/fabric-verify-end-2-end-x86_64/5259/ (2/4)</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 6/22/2017, 3:30:33 PM<br><strong>Message</strong>: <pre>Patch Set 1:

Build Started https://jenkins.hyperledger.org/job/fabric-verify-behave-x86_64/7807/ (3/4)</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 6/22/2017, 3:30:56 PM<br><strong>Message</strong>: <pre>Patch Set 1:

Build Started https://jenkins.hyperledger.org/job/fabric-verify-x86_64/13754/ (4/4)</pre><strong>Reviewer</strong>: Kostas Christidis - kostas@gmail.com<br><strong>Reviewed</strong>: 6/22/2017, 4:29:32 PM<br><strong>Message</strong>: <pre>Patch Set 1: Code-Review-2

(2 comments)

Please see comments inline.</pre><strong>Reviewer</strong>: Scott Zwierzynski - scottz@us.ibm.com<br><strong>Reviewed</strong>: 6/22/2017, 6:21:47 PM<br><strong>Message</strong>: <pre>Patch Set 1: Code-Review-1

(4 comments)</pre><strong>Reviewer</strong>: Kostas Christidis - kostas@gmail.com<br><strong>Reviewed</strong>: 6/22/2017, 6:37:48 PM<br><strong>Message</strong>: <pre>Patch Set 1:

(1 comment)</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 6/22/2017, 7:24:24 PM<br><strong>Message</strong>: <pre>Patch Set 1: Verified-1

Build Failed 

https://jenkins.hyperledger.org/job/fabric-verify-x86_64/13754/ : FAILURE

Logs: https://logs.hyperledger.org/jobbuilder/vex-yul-hyp-jenkins-1/fabric-verify-x86_64/13754

https://jenkins.hyperledger.org/job/fabric-verify-z/9408/ : SUCCESS

Logs: https://logs.hyperledger.org/jobbuilder/vex-yul-hyp-jenkins-1/fabric-verify-z/9408

https://jenkins.hyperledger.org/job/fabric-verify-end-2-end-x86_64/5259/ : SUCCESS

Logs: https://logs.hyperledger.org/jobbuilder/vex-yul-hyp-jenkins-1/fabric-verify-end-2-end-x86_64/5259

https://jenkins.hyperledger.org/job/fabric-verify-behave-x86_64/7807/ : SUCCESS

Logs: https://logs.hyperledger.org/jobbuilder/vex-yul-hyp-jenkins-1/fabric-verify-behave-x86_64/7807</pre><strong>Reviewer</strong>: Latitia Haskins - latitia.haskins@gmail.com<br><strong>Reviewed</strong>: 6/28/2017, 12:26:52 PM<br><strong>Message</strong>: <pre>Abandoned

From further discussions, it sounds like this test scenario may have inconsistent results.</pre><h1>PatchSets</h1><h3>PatchSet Number: 1</h3><blockquote><strong>Type</strong>: REWORK<br><strong>Author</strong>: Latitia Haskins - latitia.haskins@gmail.com<br><strong>Uploader</strong>: Latitia Haskins - latitia.haskins@gmail.com<br><strong>Created</strong>: 6/22/2017, 3:26:52 PM<br><strong>UnmergedRevision</strong>: [15a08023d96c133feeb4faa8a700b98f37f4653f](https://github.com/hyperledger-gerrit-archive/fabric/commit/15a08023d96c133feeb4faa8a700b98f37f4653f)<br><br><strong>Approver</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Approved</strong>: 6/22/2017, 7:24:24 PM<br><strong>Type</strong>: Verified<br><strong>Value</strong>: -1<br><br><strong>Approver</strong>: Kostas Christidis - kostas@gmail.com<br><strong>Approved</strong>: 6/22/2017, 4:29:32 PM<br><strong>Type</strong>: Code-Review<br><strong>Value</strong>: -1<br><br><strong>Approver</strong>: Scott Zwierzynski - scottz@us.ibm.com<br><strong>Approved</strong>: 6/22/2017, 6:21:47 PM<br><strong>Type</strong>: Code-Review<br><strong>Value</strong>: -1<br><br><h2>Comments</h2><strong>Commenter</strong>: Kostas Christidis - kostas@gmail.com<br><strong>CommentLine</strong>: [/COMMIT_MSG#L14](https://github.com/hyperledger-gerrit-archive/fabric/blob/15a08023d96c133feeb4faa8a700b98f37f4653f//COMMIT_MSG#L14)<br><strong>Comment</strong>: <pre>undefined</pre><strong>Commenter</strong>: Scott Zwierzynski - scottz@us.ibm.com<br><strong>CommentLine</strong>: [/COMMIT_MSG#L14](https://github.com/hyperledger-gerrit-archive/fabric/blob/15a08023d96c133feeb4faa8a700b98f37f4653f//COMMIT_MSG#L14)<br><strong>Comment</strong>: <pre>Her testcase takes does an invoke successfully with only kafka2 and kafka3 active. Then takes them down. Then restarts kafka0 and kafka1 - at which point an invoke will fail. Why don't we delete some of this confusing wording here, and let the testcase speak for itself.</pre><strong>Commenter</strong>: Kostas Christidis - kostas@gmail.com<br><strong>CommentLine</strong>: [/COMMIT_MSG#L14](https://github.com/hyperledger-gerrit-archive/fabric/blob/15a08023d96c133feeb4faa8a700b98f37f4653f//COMMIT_MSG#L14)<br><strong>Comment</strong>: <pre>None of this addresses my comment above. You are NOT guaranteed that the invocation will be successful with two brokers up. We've also had a version of this discussion in the comments of FAB-4013.</pre><strong>Commenter</strong>: Scott Zwierzynski - scottz@us.ibm.com<br><strong>CommentLine</strong>: [test/feature/orderer.feature#L124](https://github.com/hyperledger-gerrit-archive/fabric/blob/15a08023d96c133feeb4faa8a700b98f37f4653f/test/feature/orderer.feature#L124)<br><strong>Comment</strong>: <pre>lets do 4 more invokes here, to avoid confusion later when trying to interpret results</pre><strong>Commenter</strong>: Kostas Christidis - kostas@gmail.com<br><strong>CommentLine</strong>: [test/feature/orderer.feature#L127](https://github.com/hyperledger-gerrit-archive/fabric/blob/15a08023d96c133feeb4faa8a700b98f37f4653f/test/feature/orderer.feature#L127)<br><strong>Comment</strong>: <pre>In your commit message you state that you expect a failure, yet this sounds like you expect the invocation to succeed, right?</pre><strong>Commenter</strong>: Scott Zwierzynski - scottz@us.ibm.com<br><strong>CommentLine</strong>: [test/feature/orderer.feature#L127](https://github.com/hyperledger-gerrit-archive/fabric/blob/15a08023d96c133feeb4faa8a700b98f37f4653f/test/feature/orderer.feature#L127)<br><strong>Comment</strong>: <pre>THIS invoke is expected to succeed (obviously, since we are looking for 980 after the invoke, instead of looking for the old value of 990). The invoke that is expected to fail (as suggested in the commit msg) is the LAST invoke - because we restarted kafkabrokers 0 & 1 - neither of which has the latest version of the ledger.</pre><strong>Commenter</strong>: Scott Zwierzynski - scottz@us.ibm.com<br><strong>CommentLine</strong>: [test/feature/orderer.feature#L144](https://github.com/hyperledger-gerrit-archive/fabric/blob/15a08023d96c133feeb4faa8a700b98f37f4653f/test/feature/orderer.feature#L144)<br><strong>Comment</strong>: <pre>now set this to 950 (expecting the invoke to fail). And the test should pass. If desired, also can bring up kafka2 and then try anohter invoke, and confirm if you see 940.</pre></blockquote>